name: weather_app_team
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  geolocator: ^9.0.2
  build_runner: ^2.3.3
  freezed: ^2.3.2
  bloc: ^8.1.1
  dio: ^5.0.3
  envied: ^0.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  intl: ^0.17.0
  json_annotation: ^4.8.0

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
